className: "Lieu"
classIcon: "map-pin"

parentProperty:
  type: "FileProperty"
  name: "Parent"
  classes: ["Lieu"]
  icon: "map-pin"

subClassesProperty:
  name: "Type"
  subClasses:
    - name: "Commune"
      icon: "building"
    - name: "EPCI"
      icon: "buildings"
    - name: "Departement"
      icon: "map"
    - name: "Region"
      icon: "globe"
    - name: "National"
      icon: "flag"

properties:
  classe:
    type: "ClasseProperty"
    name: "Classe"
    icon: "map-pin"
  
  type:
    type: "SubClassProperty"
    name: "Type"
    icon: "landmark"
  
  parent:
    type: "FileProperty"
    name: "Parent"
    classes: ["Lieu"]
    icon: "map-pin"
  
  codePostal:
    type: "Property"
    name: "Code postal"
    icon: "hash"
  
  population:
    type: "NumberProperty"
    name: "Population"
    icon: "users"
  
  superficie:
    type: "NumberProperty"
    name: "Superficie (km²)"
    icon: "area-chart"
  
  coordonnées:
    type: "AdressProperty"
    name: "Coordonnées"
    icon: "map-pin"
  
  contacts:
    type: "MultiFileProperty"
    name: "Contacts"
    classes: ["Personne"]
    icon: "contacts"
  
  institutions:
    type: "MultiFileProperty"
    name: "Institutions"
    classes: ["Institution"]
    icon: "building"

display:
  layout: "custom"
  containers:
    - type: "line"
      className: "metadata-line"
      properties: ["classe", "parent", "type", "codePostal"]
    
    - type: "fold"
      foldTitle: "Informations géographiques"
      properties: ["population", "superficie", "coordonnées"]
    
    - type: "tabs"
      tabs:
        - name: "Contacts"
          properties: ["contacts"]
        - name: "Institutions"
          properties: ["institutions"]