className: "Note"
classIcon: "notebook-pen"

properties:
  classe:
    type: "ClasseProperty"
    name: "Classe"
    icon: "notebook-pen"
  
  date:
    type: "DateProperty"
    name: "Date"
    defaultValue: "today"
    icon: "calendar"
  
  type:
    type: "SelectProperty"
    name: "Type"
    options:
      - name: "Note"
        color: "blue"
      - name: "Rapport"
        color: "green"
      - name: "Compte-rendu"
        color: "red"
      - name: "Autre"
        color: "grey"

display:
  layout: "custom"
  containers:
    - type: "line"
      className: "metadata-line"
      properties: ["classe", "date", "type"]