className: "Test"
classIcon: "test-tube"

properties:
  - name: "classe"
    type: "ClasseProperty"
    icon: "circle-user-round"
    default: ""
  - name: "email"
    type: "EmailProperty"
    icon: "mail"
    default: ""
  - name: "phone"
    type: "PhoneProperty"
    icon: "phone"
    default: ""
  - name: "lieu"
    type: "FileProperty"
    icon: "map-pin"
    default: ""
    classes: "Lieu"
  - name: "relation"
    type: "MultiSelectProperty"
    icon: "users"
    default: ""
    options: "client:,vecteur:,expert:"
  - name: "etat"
    type: "SelectProperty"
    icon: "activity"
    default: "Pas encore contacté"
    options: "Pas encore contacté:,Prospection:,Intéressé:"

display:
  layout: "custom"
  containers:
    - type: "line"
      className: "metadata-line"
      properties: ["classe", "email", "phone"]
    
    - type: "line"
      className: "metadata-line"
      properties: ["lieu", "relation", "etat"]